// Shared products data — imported by Home.jsx, ProductCatalogSection, and ProductDetailPage

export const productsData = [
  {
    id: 'p1',
    title: 'Premium Non-Stick Cookware Set',
    brand: 'NC Nandini Collections',
    description: 'A complete 8-piece cookware set featuring premium non-stick coating, ergonomic handles, and even heat distribution for perfect results every time.',
    longDescription: 'This 8-piece non-stick cookware set is engineered for everyday excellence. The advanced PTFE non-stick coating ensures effortless food release and easy cleanup, while the triple-layer aluminum base guarantees rapid, even heat distribution across the entire cooking surface. Riveted stainless-steel handles stay cool to the touch, and every piece is compatible with gas, electric, and ceramic cooktops.',
    price: '4,999',
    category: 'cookware',
    imageKey: 'modern_cookware_set',
    features: ['8-piece complete set', 'Triple-layer aluminum base', 'PTFE non-stick coating', 'Ergonomic cool-touch handles', 'Gas, electric & ceramic compatible', 'Dishwasher safe'],
    material: 'Aluminum with PTFE coating',
    careInstruction: 'Hand wash recommended. Avoid metal utensils.',
  },
  {
    id: 'p2',
    title: 'Elegant Ceramic Bakeware Collection',
    brand: 'NC Nandini Collections',
    description: 'Beautifully crafted ceramic bakeware set with a smooth glazed finish. Oven-safe up to 450\u00b0F, perfect for casseroles, pies, and roasts.',
    longDescription: 'Each piece in this ceramic bakeware collection is hand-finished with a smooth food-safe glaze that resists stains and odors. The thick ceramic walls retain heat uniformly, ensuring your bakes cook through perfectly without hot spots. Oven-safe up to 450\u00b0F, these pieces transition effortlessly from oven to table for stunning presentation.',
    price: '3,499',
    category: 'bakeware',
    imageKey: 'elegant_bakeware_pans',
    features: ['Oven-safe up to 450\u00b0F', 'Smooth food-safe glaze', 'Uniform heat retention', 'Stain & odor resistant', 'Freezer safe', 'Microwave safe'],
    material: 'High-fired stoneware ceramic',
    careInstruction: 'Dishwasher safe. Avoid sudden temperature changes.',
  },
  {
    id: 'p3',
    title: 'Airtight Glass Storage Containers',
    brand: 'NC Nandini Collections',
    description: 'Premium borosilicate glass containers with leak-proof bamboo lids. Keep your pantry organized and your food fresh longer.',
    longDescription: 'Crafted from premium borosilicate glass, these storage containers are built to last and built to impress. The natural bamboo lids feature a silicone seal ring that creates a 100% airtight closure, keeping food fresh up to 3x longer than standard containers. The crystal-clear glass lets you see contents at a glance, and every piece is freezer, microwave, and dishwasher safe.',
    price: '2,299',
    category: 'storage',
    imageKey: 'kitchen_storage_containers_minimalist',
    features: ['Borosilicate glass body', 'Bamboo lid with silicone seal', '100% airtight closure', 'Freezer, microwave & oven safe', 'Stackable design', 'BPA-free'],
    material: 'Borosilicate glass + natural bamboo',
    careInstruction: 'Dishwasher safe (lid hand wash only).',
  },
  {
    id: 'p4',
    title: 'Damascus Steel Knife Set',
    brand: 'NC Nandini Collections',
    description: 'Hand-forged Damascus steel blades with full-tang construction and rosewood handles. A chef\'s dream set of precision instruments.',
    longDescription: 'Each blade in this set is hand-forged from 67 layers of premium Damascus steel, creating the signature flowing pattern that marks true craftsmanship. The full-tang construction ensures exceptional balance and durability, while the oil-finished rosewood handles provide a warm, secure grip. The razor-sharp edge is honed to 15\u00b0 per side for precision cutting performance that lasts.',
    price: '6,999',
    category: 'cutlery',
    imageKey: 'premium_kitchen_knives_cutlery_set',
    features: ['67-layer Damascus steel', 'Full-tang construction', 'Oil-finished rosewood handles', '15\u00b0 razor-sharp edge per side', 'Includes honing steel', 'Handcrafted in limited quantities'],
    material: '67-layer Damascus steel + rosewood',
    careInstruction: 'Hand wash only. Hone regularly. Oil handles monthly.',
  },
  {
    id: 'p5',
    title: 'Copper Core Saucepan Trio',
    brand: 'NC Nandini Collections',
    description: 'Tri-ply copper core construction for superior heat control. Three essential sizes for sauces, soups, and simmering.',
    longDescription: 'The Copper Core Saucepan Trio uses a true tri-ply bonded construction — stainless steel exterior, pure copper core, and stainless-steel interior — for the most responsive heat control available in home cookware. Whether reducing a delicate sauce or simmering a hearty soup, these pans respond instantly to temperature adjustments. Induction compatible and oven-safe to 500\u00b0F.',
    price: '5,499',
    category: 'cookware',
    imageKey: 'modern_cookware_set',
    features: ['Tri-ply copper core construction', 'Stainless steel interior & exterior', 'Induction compatible', 'Oven-safe to 500\u00b0F', 'Three essential sizes (1.5L, 2.5L, 3.5L)', 'Lifetime warranty'],
    material: 'Stainless steel + copper core',
    careInstruction: 'Dishwasher safe. Dry immediately to prevent water spots.',
  },
  {
    id: 'p6',
    title: 'Silicone Baking Mat & Mold Set',
    brand: 'NC Nandini Collections',
    description: 'Food-grade silicone mats and molds for effortless baking and easy cleanup. Non-stick, reusable, and eco-friendly.',
    longDescription: 'This comprehensive silicone baking set includes two large oven liners, a 12-cup muffin mold, and a decorative loaf mold — all crafted from premium FDA-approved food-grade silicone. The naturally non-stick surface eliminates the need for sprays or parchment paper, making every bake healthier and every cleanup a breeze. Rated for use between -40\u00b0F and 480\u00b0F.',
    price: '1,799',
    category: 'bakeware',
    imageKey: 'elegant_bakeware_pans',
    features: ['FDA-approved food-grade silicone', 'Rated -40\u00b0F to 480\u00b0F', 'Naturally non-stick surface', 'Includes 2 mats + 2 molds', 'Reusable & eco-friendly', 'Easy rollup storage'],
    material: 'FDA-approved food-grade silicone',
    careInstruction: 'Dishwasher safe. Store rolled or flat.',
  },
];
